version: "3.9"

services:
  app:
    build: .
    container_name: support-agent-app
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - ./data:/app/data  # persist logs locally

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  # persist models

volumes:
  ollama_data:
